project/config/routes.rb
Rails.application.routes.draw do
root 'posts#index'


get 'about' => 'pages#about'

resources :posts
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

project/app/models/post.rb
class Post < ApplicationRecord
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'Информация о нас!'
    end
end

project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @post = Post.all
    end

    def new

    end

    def show
        @post = Post.find(params[:id])
    end

    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)

        @post.save
        redirect_to @post
    end

    private

    def post_params
        params.require(:post).permit(:title, :body)
    end

end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/pages_helper.rb
module PagesHelper
end

project/app/helpers/posts_helper.rb
module PostsHelper
end

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-white">Illia Bordun</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
  </header>
    <%= yield %>
  </body>
</html>

project/app/views/pages/about.html.erb
<h3><%= @title %></h3>

project/app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<% @post.each do |post| %>
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
<% end %>

project/app/views/posts/new.html.erb
<h2>Добавление нового поста!</h2>
<%= form_for :post, url: posts_path do |f| %>
  <p>
  Название<br>
  <%= f.text_field :title %>
  </p>
  <p>
  Текст статьи<br>
  <%= f.text_area :body %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<% end %>

project/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>